### ISSUE TITLE
HAWKULAR_URL takes a domain, rather than a URL

### ISSUE THREAD

**Issue by bedag-moo** [RedHatQE/hawkular-docker#18]
The docs write:

```
HAWKULAR_URL=http://<hostName>
```

but the shell script does:

```
if [ -z "${HAWKULAR_URL}" ]; then
    export HAWKULAR_URL="localhost:8080"
fi
```

and indeed, if HAWULAR_URL starts with http://, Hawlukar interprets http as domain name, and the browser helpfully redirects to http://http.com/mydomain/...

**Comment by vnugent** [comment]
Thanks.  We have deprecated this project.  The new project is here: https://github.com/Hawkular-QE/hawkular-services-docker
